# PyTorch Tensors <a id="top"></a>

---
## Table of Contents

* [PyTorch Tensors Overview](#tensors_overview)
    * [Tensors vs NumPy](#vs_numpy)
* [Tensor Tutorial](#tensor_tutorial)
    * [Imports](#imports)
    * [Tensor Creation and Properties](#properties)
    * [Basic Operations](#operations)
    * [Reshaping and Slicing](#reshaping)
    * [Linear Algebra Operations and Broadcasting](#linear)
    * [GPU Acceleration with Tensors](#gpu)
    * [Calculating Gradients](#gradient)
    * [Bonus: Tensors to NumPy Arrays](#convert)

# PyTorch Tensors Overview<a class="anchor" id="tensors_overview"></a>

A Torch tensor refers to a multi-dimensional array in PyTorch, which is an open-source machine learning library primarily developed by Facebook's AI Research lab (FAIR). Tensors are fundamental data structures in PyTorch and serve as the primary building blocks for constructing neural networks and performing various mathematical operations involved in deep learning tasks.

## Tensors vs NumPy <a class="anchor" id="vs_numpy"></a>

**PyTorch Tensors**:
- **Definition**: PyTorch tensors are multi-dimensional arrays that allow us to handle data in a uniform manner. They serve as the backbone of PyTorch models.
- **Similarity to NumPy Arrays**: PyTorch tensors are conceptually similar to NumPy ndarrays. Both represent multi-dimensional arrays with uniform data types.
- **Syntax and Interface**:
    - To create PyTorch tensors, you can use the torch.tensor() method.
    - Example: `my_tensor = torch.tensor([1, 2, 3])`
- **Automatic Differentiation**: PyTorch tensors support built-in automatic differentiation using PyTorch’s Autograd module. This feature is crucial for deep learning tasks.
- **GPU Support**: PyTorch tensors can be integrated with CUDA-enabled GPUs for accelerated computation.ime.
- **Performance**: PyTorch tensors are optimized for deep learning tasks and efficient GPU acceleration.

**NumPy ndarrays**:
- **Definition**: NumPy arrays are fundamental data structures in the NumPy library for Python. They represent multi-dimensional arrays of homogeneous data.
- **Syntax and Interface**:
    - To create NumPy arrays, you can use the np.array() method.
    - Example: `my_array = np.array([1, 2, 3])`
- **Automatic Differentiation**: NumPy arrays do not support automatic differentiation out of the box.
- **GPU Support**: NumPy has limited support for GPU computation, requiring additional libraries.
- **Performance**: While efficient for general-purpose numerical computations, NumPy arrays are less optimized for deep learning.

**Comparison Summary**:
PyTorch tensors are more specialized for deep learning, while NumPy arrays are commonly used in typical machine learning algorithms.
PyTorch tensors offer advantages like GPU acceleration and automatic differentiation.
Both are powerful tools, but their use cases differ based on the context and requirements of your project.

# Tensors Tutorial <a class="anchor" id="tensor_tutorial"></a>

## Imports <a class="anchor" id="imports"></a>

In [1]:
import torch

## Basic Tensor Creation and Properties <a class="anchor" id="properties"></a>

In [8]:
# Create a 3x4 tensor filled with uninitialized values
# This will give you a tensor with random-looking values because it’s uninitialized.
# The torch.empty() call allocates memory but doesn’t initialize the values
x = torch.empty(3, 4)
print("3x4 Tensor with uninitialized values:")
print(x)

# Create a tensor filled with zeros
zeros = torch.zeros(2, 3)
print("\n2x3 Tensor of zeros:")
print(zeros)

# Create a tensor filled with ones
ones = torch.ones(2, 3)
print("\n2x3 Tensor of ones:")
print(ones)

3x4 Tensor with uninitialized values:
tensor([[-5.6875e+22,  3.0857e-41,  0.0000e+00,  0.0000e+00],
        [-5.6933e+22,  3.0857e-41, -4.7270e+21,  3.0857e-41],
        [-9.1396e+18,  4.5836e-41,  1.4013e-45,  0.0000e+00]])

2x3 Tensor of zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.]])

2x3 Tensor of ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [6]:
# Create a 1D tensor
tensor1d = torch.tensor([1, 2, 3, 4, 5])
print("1D Tensor:")
print(tensor1d)

# Create a 2D tensor
tensor2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("\n2D Tensor:")
print(tensor2d)

# Create a 2D tensor with random values between 0 and 1
random = torch.rand(2, 3)
print("\n2D Tensor of random values:")
print(random)

1D Tensor:
tensor([1, 2, 3, 4, 5])

2D Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])

2D Tensor of random values:
tensor([[0.1120, 0.0472, 0.7522],
        [0.9413, 0.0838, 0.6783]])


In [14]:
# Accessing elements
print("\nElement at index (1, 2):")
print(tensor2d[1, 2])

print("\nElement at index (0, 3):")
print(tensor2d[0, 1])


Element at index (1, 2):
tensor(6)

Element at index (0, 3):
tensor(2)


In [9]:
# Tensor shape
print("\nTensor Shape:")
print(tensor2d.shape)

# Tensor size
print("\nTensor Size:")
print(tensor2d.size())

# Tensor shape
print("\nTensor Data Type:")
print(tensor2d.dtype)


Tensor Shape:
torch.Size([2, 3])

Tensor Size:
torch.Size([2, 3])

Tensor Data Type:
torch.int64

Element at index (1, 2):
tensor(6)


In [15]:
# Create a tensor with specific data type (e.g., float64)
custom_dtype = torch.ones(2, 3, dtype=torch.float64)
print("Tensor with custom data type:")
print(custom_dtype)

Tensor with custom data type:
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


## Basic Tensor Operations <a class="anchor" id="operations"></a>

In [18]:
# Tensor addition
tensor_add = tensor1d + 10
print("Tensor Addition:")
print(tensor_add)

# Tensor subtraction
tensor_sub = tensor1d - 5
print("\nTensor Substraction:")
print(tensor_sub)

Tensor Addition:
tensor([11, 12, 13, 14, 15])

Tensor Substraction:
tensor([-4, -3, -2, -1,  0])


In [61]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# Element-wise addition
result = a + b
print("Element-wise of a + b:")
print(result)

# Element-wise subtraction
result = a - b
print("\nElement-wise of a- y:")
print(result)

# Sum all elements in the tensor
a_sum = torch.sum(a)
b_sum = torch.sum(b)
print("\nSum all elements in a:")
print(a_sum)
print("\nSum all elements in b:")
print(b_sum)

Element-wise of a + b:
tensor([5, 7, 9])

Element-wise of a- y:
tensor([-3, -3, -3])

Sum all elements in a:
tensor(6)

Sum all elements in b:
tensor(15)


In [58]:
# Element-wise multiplication
tensora_mul = a * 2
print("Tensor a Multiplication:")
print(tensora_mul)

tensorb_mul = b * 2
print("\nTensor b Multiplication:")
print(tensorb_mul)

Tensor a Multiplication:
tensor([2, 4, 6])

Tensor b Multiplication:
tensor([ 8, 10, 12])


In [31]:
# Perform element-wise operations
print("Sine of a Tensor:")
print(torch.sin(x))

print("\nExponent of a Tensor:")
print(torch.exp(x))

Sine of a Tensor:
tensor([[-3.1965e-01,  3.0857e-41,  0.0000e+00,  0.0000e+00],
        [ 9.8822e-01,  3.0857e-41,  9.2656e-02,  3.0857e-41],
        [-5.4626e-01,  4.5836e-41,  1.4013e-45,  0.0000e+00]])

Exponent of a Tensor:
tensor([[0., 1., 1., 1.],
        [0., 1., 0., 1.],
        [0., 1., 1., 1.]])


## Tensor Reshaping and Splicing <a class="anchor" id="reshaping"></a>

In [42]:
# Reshaping tensors
tensor_1d = torch.arange(12)
print("Tensor 1D:")
print(tensor_1d)

Tensor 1D:
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [51]:
# Reshaping tensors
tensor_reshape = tensor_1d.reshape(6, 2)
print("Tensor Reshaping with torch.reshape:")
print(tensor_reshape)

tensor_reshape = tensor_1d.view(3, 4)
print("\nTensor Reshaping with torch.view:")
print(tensor_reshape)

# Automatically determine size using -1
reshaped_auto = tensor_1d.view(2, -1)
print("\nTensor Reshaping with torch.view:")
print(reshaped_auto)

Tensor Reshaping with torch.reshape:
tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])

Tensor Reshaping with torch.view:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Tensor Reshaping with torch.view:
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])


In [39]:
# Slicing tensors
print("Slicing Tensor at position 0, 1:")
print(tensor_reshape[0, 1])

print("\nSlicing Tensor 1 to 3:")
print(tensor_reshape[:, 1:3])

print("\nSlicing Tensor 1 to 3:")
print(tensor_reshape[2, :])

Slicing Tensor at position 0, 1:
tensor(1)

Slicing Tensor 1 to 3:
tensor([[ 1,  2],
        [ 5,  6],
        [ 9, 10]])

Slicing Tensor 1 to 3:
tensor([ 8,  9, 10, 11])


In [ ]:
# Concatenating tensors
tensor_concat = torch.cat((tensor_reshape, tensor_reshape), dim=1)
print("\nConcatenated Tensor:")
print(tensor_concat)

## Linear Algebra Operations and Broadcasting <a class="anchor" id="linear"></a>

In [56]:
# Matrix multiplication
matrix_a = torch.tensor([[1, 2], [3, 4]])
matrix_b = torch.tensor([[5, 6], [7, 8]])
matrix_result = torch.matmul(matrix_a, matrix_b)
print("Matrix Multiplication of Matrix A and B:")
print(matrix_result)

# Matrix multiplication with transpose
# Matrix multiplication of matrix A and the transpose of matrix B computes the dot product of each row in A with each column in the transpose of B.
matrix_transpose = torch.matmul(matrix_a, matrix_b.T)
print("\nMatrix Multiplication of Matrix A and B Transpose:")
print(matrix_transpose)

# Define matrices A and B
matrix_1 = torch.tensor([[1, 2],
                         [3, 4]])

matrix_2 = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
matrix_transpose2 = torch.matmul(matrix_1, matrix_2.T)
print("\nMatrix Multiplication of Matrix 1 and 2 Transpose:")
print(matrix_transpose2)

Matrix Multiplication of Matrix A and B:
tensor([[19, 22],
        [43, 50]])

Matrix Multiplication of Matrix A and B Transpose:
tensor([[17, 23],
        [39, 53]])

Matrix Multiplication of Matrix 1 and 2 Transpose:
tensor([[ 5, 11, 17],
        [11, 25, 39]])


In [55]:
tensor_reshape = torch.arange(12).reshape(3, 4)
print("Tensor Reshaping:")
print(tensor_reshape)

# Broadcasting
tensor_broadcast = torch.tensor([[1], [2], [3]])
# Elements from each column is added to 1, 2, and 3, respectively
result = tensor_reshape + tensor_broadcast
print("\nBroadcasting:")
print(result)

Tensor Reshaping:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Broadcasting:
tensor([[ 1,  2,  3,  4],
        [ 6,  7,  8,  9],
        [11, 12, 13, 14]])


## GPU Acceleration with Tensors <a class="anchor" id="gpu"></a>

In [64]:
# Check if GPU / cuda is available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Moving tensors to GPU
tensor_gpu = tensor1d.to(device)
print("Tensor on GPU:")
print(tensor_gpu)

# Performing operations on GPU
result_gpu = tensor_gpu * 2
print("\nResult on GPU:")
print(result_gpu)

Tensor on GPU:
tensor([1, 2, 3, 4, 5], device='cuda:0')

Result on GPU:
tensor([ 2,  4,  6,  8, 10], device='cuda:0')


## Calculating Gradients <a class="anchor" id="gradient"></a>

In [65]:
# Tensor with requires_grad
tensor_grad = torch.tensor([1., 2., 3.], requires_grad=True)

# Define a computation
output = (tensor_grad * 3).sum()

# Perform backward pass
output.backward()

# Access gradients
print("Gradient of tensor_grad:")
print(tensor_grad.grad)


Gradient of tensor_grad:
tensor([3., 3., 3.])


In [80]:
a = torch.rand(1, 3)
b = torch.tensor([4., 5., 6.])
print("Random tensors of float dtype:")
print(a)
print(b)

# In-place addition
a.add_(b)
print("\nIn-place addition:")
print(a)

# Enable gradient tracking for optimization
a.requires_grad = True
print("\nEnable gradient:")
print(a)

# Perform some operations (e.g., loss computation)
loss = (a * 2).sum()
print("\nCompute Loss with Sum:")
print(loss)

loss.backward()  # Compute gradients
print("\nLoss after Gradients:")
print(loss)

Random tensors of float dtype:
tensor([[0.4256, 0.0898, 0.4951]])
tensor([4., 5., 6.])

In-place addition:
tensor([[4.4256, 5.0898, 6.4951]])

Enable gradient:
tensor([[4.4256, 5.0898, 6.4951]], requires_grad=True)

Compute Loss with Sum:
tensor(32.0210, grad_fn=<SumBackward0>)

Loss after Gradients:
tensor(32.0210, grad_fn=<SumBackward0>)


## Bonus: Tensors to NumPy Arrays <a class="anchor" id="convert"></a>

In [69]:
random_tensor = torch.rand(3, 4)

numpy_array = random_tensor.numpy()
print("Random Tensor to NumPy Array:")
print(numpy_array)
# Do operations on the NumPy array
# ...

# Convert back to PyTorch tensor
tensor_from_numpy = torch.from_numpy(numpy_array)
print("\nNumPy Array Back to Tensor:")
print(numpy_array)

Random Tensor to NumPy Array:
[[0.47379214 0.1305232  0.15354198 0.9151255 ]
 [0.6240082  0.39175177 0.20841885 0.21017677]
 [0.09977621 0.07718092 0.83010954 0.8067131 ]]

NumPy Array Back to Tensor:
[[0.47379214 0.1305232  0.15354198 0.9151255 ]
 [0.6240082  0.39175177 0.20841885 0.21017677]
 [0.09977621 0.07718092 0.83010954 0.8067131 ]]


**[Go to Top](#top)**